test_gui_acceptance_followup <- function(ctx) {
  record_test("ml_union_only_rf", {
    rf <- paste0("RF", 1:3)
    expect_equal(select_ml_feature_ids("union", list(rf = rf, l1 = NULL, rfl1 = NULL), 50), rf, "Union changed the only available RF result")
  })
  record_test("ml_union_only_l1", {
    l1 <- paste0("L1", 1:3)
    expect_equal(select_ml_feature_ids("union", list(rf = NULL, l1 = l1, rfl1 = NULL), 50), l1, "Union changed the only available L1 result")
  })
  record_test("ml_union_only_rfl1", {
    rfl1 <- paste0("RFL1", 1:3)
    expect_equal(select_ml_feature_ids("union", list(rf = NULL, l1 = NULL, rfl1 = rfl1), 50), rfl1, "Union changed the only available RF+L1 result")
  })
  record_test("ml_union_multiple_sources", {
    rf <- c("A", "B"); l1 <- c("B", "C"); rfl1 <- c("C", "D")
    expect_equal(select_ml_feature_ids("union", list(rf = rf, l1 = l1, rfl1 = rfl1), 50), c("A", "B", "C", "D"), "Union did not use deterministic set-union order")
  })
  ids <- paste0("P", sprintf("%03d", 1:12))
  sets <- list(GroupA = c(ids[1:8], ids[9]), GroupB = c(ids[1:8], ids[10]), GroupC = c(ids[1:8], ids[11:12]))
  record_test("upset_three_group_heavy_overlap", {
    d <- file.path(ctx$outputs, "upset_followup"); dir.create(d, recursive = TRUE)
    m <- make_set_membership(sets)
    expect_equal(sum(m$GroupA == 1 & m$GroupB == 1 & m$GroupC == 1), 8L, "Unexpected three-group intersection")
    expect_equal(setequal(names(sets), colnames(m)[-1]), TRUE, "UpSet group columns changed")
    plot_venn_upset(sets, d, width = 4, height = 4)
    expect_file_nonempty(file.path(d, "upset.pdf")); expect_file_nonempty(file.path(d, "venn.pdf"))
  })
  record_test("upset_intersection_count_labels", {
    m <- make_set_membership(sets)
    plotted <- upset_intersection_data(m)
    expect_true(length(plotted$values) > 0, "UpSet intersection data is empty")
    expect_equal(sum(plotted$values), nrow(m), "Plotted intersection counts do not cover the membership table")
    expect_equal(length(plotted$labels), length(plotted$values), "UpSet labels and bars are not one-to-one")
    triple <- match("111", plotted$labels)
    expect_true(!is.na(triple), "Triple intersection bar is missing")
    expect_equal(plotted$values[[triple]], 8L, "Triple intersection count label differs from bar count")
  })
  ann <- data.frame(Accession = ids[1:10], GRAVY = seq(-1, 1, length.out = 10), TM_helices = 0:9, MW = 50:59, pI = 6:15, Length = 100:109, Subcellular_class = rep(c("Cytosol", "Membrane"), 5))
  af <- file.path(ctx$fixtures, "annotation_followup.csv"); data.table::fwrite(ann, af)
  record_test("annotation_three_group_preservation", {
    d <- file.path(ctx$outputs, "annotation_followup"); dir.create(d, recursive = TRUE)
    result <- run_physicochemical(sets, af, d, width = 3, height = 3)
    expect_set_equal(unique(result$data$Group), names(sets), "Annotation group labels were not preserved")
    cov <- data.table::fread(file.path(d, "annotation_mapping_coverage.csv"), data.table = FALSE)
    expect_columns_include(cov, c("Group", "Queried_Proteins", "Matched_Proteins", "Unmatched_Proteins", "Match_Percent"))
    expect_equal(cov$Matched_Proteins, c(9L, 9L, 8L), "Annotation coverage counts differ")
  })
  record_test("annotation_low_match_coverage", {
    d <- file.path(ctx$outputs, "annotation_low"); dir.create(d, recursive = TRUE)
    result <- run_physicochemical(lapply(sets, function(x) c(x[1], "UNMATCHED")), af, d, width = 3, height = 3)
    expect_true(all(result$coverage$Match_Percent < 100), "Partial annotation mismatch was not reported")
    expect_set_equal(unique(result$data$Group), names(sets), "Low-coverage annotation changed group labels")
  })
  record_test("annotation_zero_match_no_fake_group", {
    d <- file.path(ctx$outputs, "annotation_zero"); dir.create(d, recursive = TRUE)
    err <- tryCatch({ run_physicochemical(lapply(sets, function(x) "NO_MATCH"), af, d); NULL }, error = identity)
    expect_true(!is.null(err) && grepl("No proteins could be matched", conditionMessage(err), fixed = TRUE), "Zero-match annotation did not return a clear message")
    cov <- data.table::fread(file.path(d, "annotation_mapping_coverage.csv"), data.table = FALSE)
    expect_equal(sum(cov$Matched_Proteins), 0L, "Zero-match coverage was not exact")
    expect_false(any(grepl("Group1", cov$Group, fixed = TRUE)), "Zero-match path fabricated Group1")
  })
  rank_mat <- matrix(c(99, 0, NA, 10, 5, 0, 1, NA, 0, 20, 2, 3), nrow = 4, dimnames = list(paste0("R", 1:4), paste0("S", 1:3)))
  rank_groups <- make_group_info(colnames(rank_mat), c("A", "A", "B"))
  record_test("rank_abundance_na_exclusion", {
    d <- file.path(ctx$outputs, "rank_na"); dir.create(d, recursive = TRUE)
    x <- plot_rank_abundance(rank_mat, rank_groups, file.path(d, "rank.pdf"), file.path(d, "rank.csv"), width = 3, height = 3, transform = "log10")
    expect_true(!any(is.na(x$Raw_Abundance)), "NA abundance entered rank data"); expect_equal(nrow(x), sum(!is.na(rank_mat)), "NA values were not excluded")
  })
  record_test("rank_abundance_zero_valid", {
    d <- file.path(ctx$outputs, "rank_zero"); dir.create(d, recursive = TRUE)
    x <- plot_rank_abundance(rank_mat, rank_groups, file.path(d, "rank.pdf"), file.path(d, "rank.csv"), width = 3, height = 3, transform = "log2")
    expect_true(any(x$Raw_Abundance == 0), "Valid zero was removed"); expect_true(all(abs(x$Transformed_Abundance[x$Raw_Abundance == 0]) <= 1e-12), "Valid zero did not transform to zero")
  })
  record_test("rank_abundance_log2_log10_parity", {
    d <- file.path(ctx$outputs, "rank_transforms"); dir.create(d, recursive = TRUE)
    x2 <- plot_rank_abundance(rank_mat, rank_groups, file.path(d, "log2.pdf"), file.path(d, "log2.csv"), width = 3, height = 3, transform = "log2")
    x10 <- plot_rank_abundance(rank_mat, rank_groups, file.path(d, "log10.pdf"), file.path(d, "log10.csv"), width = 3, height = 3, transform = "log10")
    expect_equal(x2$ProteinID, x10$ProteinID, "Transform changed rank ordering"); expect_equal(x2$Rank, x10$Rank, "Transform changed ranks"); expect_near(x10$Transformed_Abundance[x10$Raw_Abundance == 99], 2, message = "log10(+1) sanity check failed")
    expect_file_nonempty(file.path(d, "log2.pdf")); expect_file_nonempty(file.path(d, "log10.pdf"))
  })
}
