test_ml <- function(ctx) {
  if (!require_namespace_or_skip("randomForest", "ML regression")) return(invisible(NULL))
  if (!require_namespace_or_skip("glmnet", "ML regression")) return(invisible(NULL))
  f <- make_binary_ml_fixture(seed = 2026, n_features = 320, n_per_group = 12)
  out <- file.path(ctx$outputs, "ml_binary")
  record_test("ml_binary_rf", { d <- file.path(out, "rf"); dir.create(d, recursive = TRUE); run_random_forest_selection(f$quantity, f$group_info, d, top_n = 20, rf_ntree = 40, seed = 2026, split_mode = "cross_validation_only", allow_small_sample = FALSE, stability_repeats = 4, stability_sample_fraction = 0.8, stability_top_var_n = 100); x <- data.table::fread(file.path(d, "random_forest_stability_selection.csv"), data.table = FALSE); expect_no_duplicates(x$ProteinID, "RF stability proteins"); expect_true(all(is.finite(x$StabilityScore)), "RF stability scores contain non-finite values"); p <- data.table::fread(file.path(d, "random_forest_stability_resample_performance.csv"), data.table = FALSE); expect_columns_exclude(p, c("cv_folds", "RequestedCVFolds", "EffectiveCVFolds"), "RF performance") })
  record_test("ml_binary_l1", { d1 <- file.path(out, "l1_1"); d2 <- file.path(out, "l1_2"); for (d in c(d1, d2)) { dir.create(d, recursive = TRUE); run_l1_selection(f$quantity, f$group_info, d, top_n = 20, seed = 2026, split_mode = "cross_validation_only", allow_small_sample = FALSE, stability_repeats = 4, stability_sample_fraction = 0.8, stability_top_var_n = 100, cv_folds = "Auto") }; a <- data.table::fread(file.path(d1, "l1_stability_selection.csv"), data.table = FALSE); b <- data.table::fread(file.path(d2, "l1_stability_selection.csv"), data.table = FALSE); expect_equal(a, b, "standalone L1 repeated output"); s <- data.table::fread(file.path(d1, "l1_feature_selection_ml_settings.csv"), data.table = FALSE); expect_true(any(s$Setting == "L1Family" & s$Value == "binomial"), "Binary L1 family is not binomial"); p <- data.table::fread(file.path(d1, "l1_stability_resample_performance.csv"), data.table = FALSE); expect_columns_include(p, c("RequestedCVFolds", "EffectiveCVFolds"), "L1 performance"); expect_true(all(p$EffectiveCVFolds == 5), "Auto L1 folds did not resolve to 5 for this fixture") })
  record_test("ml_binary_rf_l1", { d <- file.path(out, "rfl1"); dir.create(d, recursive = TRUE); run_feature_selection(f$quantity, f$group_info, d, top_n = 20, rf_ntree = 40, seed = 2026, split_mode = "cross_validation_only", allow_small_sample = FALSE, stability_repeats = 4, stability_sample_fraction = 0.8, stability_top_var_n = 100, cv_folds = "Auto"); x <- data.table::fread(file.path(d, "combined_stability_scores.csv"), data.table = FALSE); expect_no_duplicates(x$ProteinID, "RF+L1 proteins"); expect_true(all(is.finite(x$StabilityScore)), "RF+L1 scores contain non-finite values"); s <- data.table::fread(file.path(d, "rf_l1_combined_feature_selection_ml_settings.csv"), data.table = FALSE); expect_true(any(s$Setting == "L1Family" & s$Value == "binomial"), "RF+L1 binary family is not binomial") })
  record_test("ml_cv_fold_policy", { y <- factor(rep(c("A", "B"), each = 12)); expect_equal(resolve_l1_folds(y, "Auto", FALSE)$nfolds, 5, "Auto fold policy"); expect_equal(resolve_l1_folds(y, 7, FALSE)$nfolds, 7, "Explicit fold policy") })
  record_test("ml_multiclass_l1", { f3 <- make_multiclass_fixture(seed = 303, n_features = 320, n_per_group = 10); d <- file.path(ctx$outputs, "ml_multiclass_l1"); dir.create(d, recursive = TRUE); run_l1_selection(f3$quantity, f3$group_info, d, top_n = 20, seed = 2026, split_mode = "cross_validation_only", allow_small_sample = FALSE, stability_repeats = 3, stability_sample_fraction = 0.8, stability_top_var_n = 100, cv_folds = "Auto"); s <- data.table::fread(file.path(d, "l1_feature_selection_ml_settings.csv"), data.table = FALSE); expect_true(any(s$Setting == "L1Family" & s$Value == "multinomial"), "Multiclass L1 family is not multinomial") })
}
