test_analysis_outputs <- function(ctx) {
  f <- make_binary_ml_fixture(seed = 707, n_features = 80, n_per_group = 6)
  g <- f$group_info
  record_test("quantitative_correlation", { d <- file.path(ctx$outputs, "cor"); dir.create(d, recursive = TRUE); plot_correlation_heatmap(f$quantity, g, file.path(d, "cor.pdf"), file.path(d, "cor.csv"), method = "pearson", order_mode = "original", width = 3, height = 3); m <- as.matrix(data.table::fread(file.path(d, "cor.csv"), data.table = FALSE)); expect_file_nonempty(file.path(d, "cor.pdf")); expect_true(nrow(m) >= 1, "Correlation output is empty") })
  record_test("quantitative_rank_cv", { d <- file.path(ctx$outputs, "rankcv"); dir.create(d, recursive = TRUE); plot_rank_abundance(f$quantity, g, file.path(d, "rank.pdf"), file.path(d, "rank.csv"), width = 3, height = 3); plot_cv_ridges(f$quantity, g, file.path(d, "cv.pdf"), file.path(d, "cv.csv"), width = 3, height = 3); expect_file_nonempty(file.path(d, "rank.pdf")); expect_file_nonempty(file.path(d, "cv.pdf")) })
  record_test("differential_limma", { d <- file.path(ctx$outputs, "volcano"); dir.create(d, recursive = TRUE); run_volcano(f$quantity, g, "A", "B", file.path(d, "volcano.pdf"), file.path(d, "volcano.csv"), test_method = "limma", width = 3, height = 3); expect_file_nonempty(file.path(d, "volcano.pdf")); x <- data.table::fread(file.path(d, "volcano.csv"), data.table = FALSE); expect_columns_include(x, c("ProteinID", "log2FC")) })
  record_test("heatmap_expression", { d <- file.path(ctx$outputs, "heatmap"); dir.create(d, recursive = TRUE); plot_expression_heatmap(f$quantity, g, file.path(d, "expression.pdf"), file.path(d, "expression.csv"), top_n = 20, row_cluster = "none", col_cluster = "none", width = 3, height = 3); expect_file_nonempty(file.path(d, "expression.pdf")) })
  record_test("annotation_offline", { d <- file.path(ctx$outputs, "annotation"); dir.create(d, recursive = TRUE); ann <- data.frame(Accession = rownames(f$quantity)[1:10], GRAVY = seq(-1, 1, length.out = 10), TM_helices = 0:9, MW = 50:59, pI = 6:15, Length = 100:109, Subcellular_class = rep(c("Cytosol", "Membrane"), 5)); af <- file.path(ctx$fixtures, "annotation.csv"); data.table::fwrite(ann, af); sets <- list(A = rownames(f$quantity)[1:10], B = rownames(f$quantity)[11:20]); run_physicochemical(sets, af, d, width = 3, height = 3); expect_true(length(list.files(d, pattern = "[.]pdf$")) > 0, "Annotation PDF missing") })
}
