coalesce_null <- function(a, b) if (!is.null(a)) a else b
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep('^--file=', args, value = TRUE)
script_path <- if (length(file_arg) > 0) normalizePath(sub('^--file=', '', file_arg[1]), winslash = '/', mustWork = TRUE) else normalizePath(coalesce_null(sys.frame(1)$ofile, 'tools/self_test_v2.R'), winslash = '/', mustWork = FALSE)
package_root <- normalizePath(file.path(dirname(script_path), '..'), winslash = '/', mustWork = TRUE)
app_root <- file.path(package_root, 'app')
setwd(app_root)
source('R/analysis_core.R')
`%||%` <- function(a, b) if (!is.null(a)) a else b
out <- file.path(package_root, 'outputs', 'self_test')
dir.create(out, recursive = TRUE, showWarnings = FALSE)
d <- extract_protein_data('F:/test/DIANNreport.pg_matrix.tsv', 'DIANN', 'd', 'protein_name')
g <- make_group_info(d$samples, rep(c('G1','G2'), each = 4))
plot_identification_bar(d$counts, g, file.path(out, 'id_bar.pdf'), file.path(out, 'id_summary.csv'), 3, 3)
run_slingshot_pseudotime(d$quantity, g, file.path(out, 'slingshot'), reduction = 'PCA', start_group = 'G1', end_group = 'G2', width = 4, height = 4)
run_physicochemical(identified_by_group(d$qualitative, g, 1), file.path(app_root, 'annotations', 'uniprot_all_celegans_6239_annotations.csv'), file.path(out, 'phys'), 3, 3)
cat('SELF_TEST_OK', nrow(d$quantity), ncol(d$quantity), '\n')
